version: '2'
services:
  final:
    image: absolutapps/oracle-12c-ee
    restart: unless-stopped
    ports:
      - 59161:1521
      - 18080:8080
      - 15500:5500

  mongo:
    image: mongo:4.0.9-xenial
    command: mongod
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=itmo_db
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=itmo_user
      - MONGO_INITDB_ROOT_PASSWORD=itmo_pass
    ports:
      - 27017:27017

  postgres:
    image: postgres:11.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - 15432:5432

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    restart: unless-stopped
    environment:
      - ORACLE_SID=itmoSID
      - ORACLE_PWD=itmo_pass

    ports:
      - 49161:1521
      - 8080:8080
      - 5500:5500

  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=itmo_db
      # provide your credentials here
      - MYSQL_USER=itmo_user
      - MYSQL_PASSWORD=itmo_pass
      - MYSQL_ROOT_PASSWORD=itmo_pass
    ports:
      - 13306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

